kind: Template
apiVersion: v1
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: egress-pod
    labels:
      name: egress-pod
    annotations:
      pod.network.openshift.io/assign-macvlan: true
  spec:
    containers:
    - name: egress-router
      image: openshift/origin-egress-router
      securityContext:
        privileged: true
      env:
      - name: EGRESS_SOURCE 
        value: 192.168.12.99
      - name: EGRESS_GATEWAY 
        value: 192.168.12.1
      - name: EGRESS_DESTINATION 
        value: 203.0.113.25
- apiVersion: v1
  kind: Service
  metadata:
    name: egress-svc
  spec:
    ports:
    - name: test
      port: 9999
    type: ClusterIP
    selector:
      name: egress-pod        
parameters:
  - name: EGRESS_SOURCE 
    description: ip from node cidr that is available for node. 
    required: true 
  - name: EGRESS_GATEWAY
    description: ip of the gateway, must be the same as the node gateway
    required: true
  - name: EGRESS_DESTINATION
    description: ip of the destination
    required: true    
